add_newline = false

format = """\
[](bg:bg fg:#7DF9AA)[ ](bg:#7DF9AA)\
[󰍲 ](bg:#7DF9AA fg:#090c0c)\
[](fg:#7DF9AA bg:#1C3A5E)\
$time\
[](fg:#1C3A5E bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#06D6A0)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#06D6A0 bg:#CC6B00)\
$python\
$java\
$kotlin\
$nodejs\
[](fg:#CC6B00 bg:bg)\
$character\
"""

[directory]
format = "[ 󰉋 $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#06D6A0"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#06D6A0"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#06D6A0"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
min_time = 500
format = "[$duration]($style)"
style = "fg:#7DF9AA"
disabled = false

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%I:%M %p" # 12-Hour Format with AM/PM
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[username]
show_always = false
format = "[ $user ]($style)"
style = "fg:#E4E4E4 bg:#1C3A5E"
disabled = false

[hostname]
ssh_only = false
format = "[ $hostname ]($style)"
style = "fg:#E4E4E4 bg:#1C3A5E"
disabled = false

[status]
format = "[✗ $status ]($style)"
style = "fg:#E84D44 bg:bg"
disabled = false
pipestatus = true

[python]
format = "[ 󰌠 $version ($virtualenv) ]($style)"
style = "fg:#E4E4E4 bg:#CC6B00"
disabled = false

[java]
format = "[ 󰬷 $version ]($style)"
style = "fg:#E4E4E4 bg:#CC6B00"
disabled = false
detect_extensions = ["java"]
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts"]

[kotlin]
format = "[  $version ]($style)"
style = "fg:#E4E4E4 bg:#CC6B00"
disabled = false
detect_extensions = ["kt", "kts"]
detect_files = ["build.gradle.kts"]

[nodejs]
format = "[ 󰎙 $version ]($style)"
style = "fg:#E4E4E4 bg:#CC6B00"
disabled = false
